#!/bin/sh

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

for x in mount umount pacman su ; do
  alias $x="sudo $x"
done

# devops starter pack
alias \
  d="docker" \
  dc="docker-compose"

alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  mkd="mkdir -pv" \
  ffmpeg="ffmpeg -hide_banner" \
  ..="cd .."
alias \
  ls="ls --color=auto --group-directories-first" \
  la="ls -a" \
  ll="ls -lah" \
  grep="grep --color=auto" \
  diff="diff --color=auto"

alias \
  ka="killall" \
  e="$EDITOR" \
  v="$EDITOR" \
  p="sudo pacman" \
  z="zathura" \
  wb="w3m -B"

alias \
  cfn="nvim ~/.config/nvim/init.vim" \
  cfd="nvim ~/.config/dwm/config.h" \
  cfdd="nvim ~/.config/dwmblocks/config.h" \
  cfs="nvim ~/.config/st/config.h"

alias \
  zar='source $ZDOTDIR/aliasrc' \
  zpr='source $ZDOTDIR/profile' \
  zrr='source $ZDOTDIR/.zshrc' \
  zae='nvim $ZDOTDIR/aliasrc' \
  zpe='nvim $ZDOTDIR/profile' \
  zre='nvim $ZDOTDIR/.zshrc'

alias \
  gs="git status" \
  gss="git status -v | $PAGER" \
  ga="git add" \
  gr="git restore --staged" \
  gc="git commit -m" \
  gp="git push -u origin main"

alias \
  ddt="git --git-dir=$HOME/.config/dotfiles/ --work-tree=$HOME" \
  ds="ddt status" \
  dss="ddt status -v | $PAGER" \
  da="ddt add" \
  doc="ddt commit -m" \
  dp="ddt push -u origin main"

alias \
  gvim="vim" \
  lf="lfub"

alias \
	godc="deadcode ./..." \
	golint="golangci-lint run --fix ./..." \
	gofield="fieldalignment -fix ./..." \
	gofieldinstall="go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest" \
	gowsl="wsl --fix ./..."


lfcd () {
  tmp="$(mktemp)"
  lf -last-dir-path="$tmp" "$@"
  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp"
    if [ -d "$dir" ]; then
      if [ "$dir" != "$(pwd)" ]; then cd "$dir"
      fi
    fi
  fi
}

bindkey -s '^o' 'lfcd\n'

alias \
  ytv="youtube-dl -f bestvideo+bestaudio" \
  yta="youtube-dl -f 'bestaudio' --ignore-errors --continue --playlist-random --no-overwrites --extract-audio --audio-format mp3 --prefer-avconv --add-metadata --output '%(title)s.%(ext)s'"

alias \
  csql="clickhouse-cli"

alias \
	k="kubectl"

export KNS="-n=seller-wb-balance"
alias \
	kgp="kubectl get po $KNS | grep -wv 'seller-wb-balance'" \
	kd="kubectl describe po $KNS"\
	klp="kubectl logs --previous $KNS" \
  kdr="kubectl describe resourcequota $KNS" \
	klf="kubectl logs --follow $KNS" \
  tst="tsh kube login k8s.stage-dp" \
  txc="tsh kube login k8s.stage-xc" \
	tdp="tsh kube login k8s.portal-dp" \
	tdl="tsh kube login k8s.portal-dl" \
	tel="tsh kube login k8s.portal-el" \
	tbel="tsh kube login k8s.wb-balance-el" \
	tbnb="tsh kube login k8s.wb-balance-nb" \
	tbxs="tsh kube login k8s.wb-balance-xs"

function ked () {
  KUBEEDITOR='vim' kubectl edit "deploy/$1" $KNS
}

function ksd () {
	kubectl scale deploy $1 --replicas=$2 $KNS
}

alias \
	wbgl="pass otp otp/gitlab.wildberries.ru -c"

function kpf () {
	kubectl $KNS port-forward svc/$1 $2
}

