#!/bin/sh

export GTK_IM_MODULE="fcitx5"
export QT_IM_MODULE="fcitx5"
export SDL_IM_MODULE="fcitx5"
export XMODIFIERS="@im=fcitx5"

# keymaps
xmodmap -e "keycode 104 = Enter"
xset r rate 300 50
xrdb $XDG_CONFIG_HOME/x11/xresources

# bg
fcitx5 -d &
mpd &
unclutter &
dwmblocks &
exec dwm
