#!/bin/sh

export GTK_IM_MODULE="fcitx5"
export QT_IM_MODULE="fcitx5"
export SDL_IM_MODULE="fcitx5"
export XMODIFIERS="@im=fcitx5"

# keymaps
xset r rate 300 50
xrdb $XDG_CONFIG_HOME/x11/xresources

# bg
fcitx5 -d &
feh --bg-fill --randomize ~/.local/share/wallpaper/nature/* &
mpd &
unclutter &
dunst &
dwmblocks &
exec dwm
