#!/bin/sh

export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
export SDL_IM_MODULE="fcitx"
export GLFW_IM_MODULE="ibus"
export XMODIFIERS="@im=fcitx"

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# keymaps
xrdb "$XDG_CONFIG_HOME/x11/xresources"
nginx -c "$XDG_CONFIG_HOME/nginx/shared" -p "$HOME/shared/"
xsetroot -bg '#000000' &

# b
remaps.sh &
fcitx5 -d &
redshift &
# feh --bg-fill --randomize ~/.local/share/wallpaper/active/* &
mpd &
unclutter &
picom &
# gazou & # japanese ocr
# syncthing --no-browser &
dunst &
dwmblocks &
sxhkd &
wallpaper-gradient-time.sh &
"$HOME/.fehbg" &
#wallpaper.sh &
#exec openbox-session
exec dwm
