#!/bin/sh

log=$XDG_DATA_HOME/atl/log
sound=$XDG_DATA_HOME/atl/sound.mp3

n=$(tail -n 1 "$log")
n_status=${n%%,*}
n_act=${n##*,}
n_time=${n#*,}
n_time=${n_time%,*}

diff=$(($(date "+%s") - n_time))
[ "$n_status" = 'start' ] && icon="🍅" || icon="💤"

seconds=$((diff % 60))
minutes=$((diff / 60 % 60))
hours=$((diff / 3600))

if [ "$icon" = "🍅" ] ; then
  target=${n_act#time}
  if [ "$minutes" -ge "$target" ]; then
    echo "end,$(($(date "+%s") - 1)),$n_act" >> "$log"

    dunstify "Pomodoro" "Your timer is over"
    pkill -RTMIN+15 dwmblocks
    mpg123 -q "$sound"
    exit 0
  fi
fi


if [ $minutes = '0' ]; then
  time="${seconds}s"
elif [ $hours = '0' ]; then
  time="${minutes}m ${seconds}s"
else
  time="${hours}h ${minutes}m"
fi

printf "%s%s%s" "$icon" "$time" "$( [ "$n_status" = "start" ] && echo " 😋$target"m || echo " ago" )"
