#!/bin/sh

[ -n "$(pidof openvpn)" ] && status="🔒" || exit 0
response=$(curl -s ipinfo.io --silent --connect-timeout 30 --max-time 30)
[ $? != 0 ] && down="🔴"
REGION="$(echo "$response" | jq -r .country)"

printf "%s%s" "$status" "$REGION"
